export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_REGIONS = "GET_REGIONS";
export const GET_CITIES = "GET_CITIES";
export const OPEN_NAV = "OPEN_NAV";
export const CLOSE_NAV = "CLOSE_NAV";
export const SET_ACTIVE_LINK = "SET_ACTIVE_LINK";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_LEAGUES = "GET_LEAGUES";
export const GET_SUB_LEAGUES = "GET_SUB_LEAGUES";
export const GET_CURRENT_LEAGUE = "GET_CURRENT_LEAGUE";

export const GET_STUFF_TYPES = "GET_STUFF_TYPES";
export const GET_STUFF_MEMBERS = "GET_STUFF_MEMBERS";
export const GET_STUFF_MEMBERS_BY_NAME = "GET_STUFF_MEMBERS_BY_NAME";
export const MERGE_STUFF = "MERGE_STUFF";

export const GET_USERS = "GET_USERS";
export const GET_USERS_BY_NAME = "GET_USERS_BY_NAME";

export const GET_TOURNAMENTS = "GET_TOURNAMENTS";
export const GET_SEASONS = "GET_SEASONS";
export const GET_SUBTOURNAMENTS = "GET_SUBTOURNAMENTS";

export const GET_POSITION = "GET_POSITION";
export const GET_PLAYERS = "GET_PLAYERS";
export const GET_PLAYERS_BY_NAME = "GET_PLAYERS_BY_NAME";
export const MERGE_PLAYER = "MERGE_PLAYER";
export const GET_MERGING = "GET_MERGING";

export const GET_COMMANDS_BY_NAME = "GET_COMMANDS_BY_NAME";
